# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    env:
      QGC_CREDENTIALS: "${{ secrets.QGC_CREDENTIALS }}"
      QGC_URL: "${{ secrets.QGC_URL }}"
      QGC_ORGANIZATION_ID: "${{ secrets.QGC_ORGANIZATION_ID }}"
      QGC_COMPONENT_ID: "${{ secrets.QGC_COMPONENT_ID }}"
    runs-on: ubuntu-latest

    steps:
    - name: Cache local Maven repository
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Build with Maven
      run: |-
        mvn -B package --file pom.xml
        ./.github/workflows/upload-evidences.sh
    - name: Trigger SCA in QGC
      run: |-
        curl --user "${QGC_CREDENTIALS}" \
          "${QGC_URL}/api/applications/${QGC_ORGANIZATION_ID}/componentqg/SOURCE_CODE_ANALYSIS/components/${QGC_COMPONENT_ID}/execution" \
          -H "Content-Type: application/json" \
          -d "{\"branchName\":\"${GITHUB_REF}\",\"gitUrl\":\"${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}.git\",\"qualityGateName\":\"Sonar way\"}"
